# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/backtest_sample',
                'doc_host': 'https://silvaac.github.io',
                'git_url': 'https://github.com/silvaac/backtest_sample',
                'lib_path': 'backtest_sample'},
  'syms': { 'backtest_sample.auto': { 'backtest_sample.auto.mysql': ('data.mysql.html#mysql', 'backtest_sample/auto.py'),
                                      'backtest_sample.auto.mysql.__init__': ('data.mysql.html#mysql.__init__', 'backtest_sample/auto.py'),
                                      'backtest_sample.auto.mysql._read_mysql': ( 'data.mysql.html#mysql._read_mysql',
                                                                                  'backtest_sample/auto.py'),
                                      'backtest_sample.auto.mysql.raw_data': ('data.mysql.html#mysql.raw_data', 'backtest_sample/auto.py'),
                                      'backtest_sample.auto.mysql.sim_data': ('data.mysql.html#mysql.sim_data', 'backtest_sample/auto.py')},
            'backtest_sample.core': {'backtest_sample.core.foo': ('core.html#foo', 'backtest_sample/core.py')}}}
