# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/data_interface.ipynb.

# %% auto 0
__all__ = ['get_class', 'get_data', 'get_er', 'get_risk', 'get_tc']

# %% ../nbs/data_interface.ipynb 4
import importlib
import os

# %% ../nbs/data_interface.ipynb 5
def get_class(source,where):
    """
    Dynamically import a class from a file.
    
    Parameters:
    - source: The name of the class within data (and the file without .py extension).
    Note the convention: class and file name are equal
    - where: folder path
    
    Returns:
    - Ouput the class.
    """
    # Construct the module name from the folder path and class name
    module_name = f"backtest_sample.{where}.{source}"
    
    try:
        # Dynamically import the module
        module = importlib.import_module(module_name)
        
        # Get the class from the module
        cls = getattr(module, source)
        
        # Create an instance of the class
        #instance = cls()
        
        # Call the output method and return the result
        return cls
    except ModuleNotFoundError:
        raise ValueError(f"Module '{module_name}' not found.")
    except AttributeError:
        raise ValueError(f"Class '{where}' not found in module '{module_name}'.")




# %% ../nbs/data_interface.ipynb 6
def get_data(source="yahoo",where="data"):
    return get_class(source,where)

def get_er(source="ma_model",where='er'):
    return get_class(source,where)

def get_risk(source="sig_model",where='risk'):
    return get_class(source,where)

def get_tc(source="simple",where='tc'):
    return get_class(source,where)
