# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/data.mysql.ipynb.

# %% auto 0
__all__ = ['mysql']

# %% ../../nbs/data.mysql.ipynb 4
from sqlalchemy import create_engine
import pandas as pd

# %% ../../nbs/data.mysql.ipynb 5
class mysql:
    def __init__(self,ticker,start_date="1900-01-01"):
        self.ticker = ticker
        self.start_date = start_date
        self.data = None
    def _read_mysql(self): # DID NOT CHECK THIS: JUST A PLACE HOLDER
        """
        Reads data from a SQL Server database.

        """
        sql_server_conn_string = "" # DOTO
        query = f"SELECT * from prices where ticker={self.ticker} and datetime>\"{self.start_date}\""
        try:
            engine = create_engine(self.sql_server_conn_string)
            self.data = pd.read_sql(query, engine)
        except Exception as e:
            print(f"Error reading data from SQL Server: {e}")

    def raw_data(self):
        self._read_mysql()    
        return self.data
    def sim_data(self):
         if self.data is None:
            self._read_mysql() 
        ### DO SOMETHING ###
        ### return data....
