# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/tc.simple.ipynb.

# %% auto 0
__all__ = ['simple']

# %% ../../nbs/tc.simple.ipynb 4
import pandas as pd
import numpy as np

# %% ../../nbs/tc.simple.ipynb 5
class simple():
    def __init__(self,data,param):
        self.ohlcv = data # this assumes a very specific format... note, more sofisticated code should take this into account
        self.slope = param['tc_slope']
        self.bias  = param['tc_bias']
    def TC(self,trade):
        V = self.ohlcv[:,5]
        p = self.ohlcv[:,4]
        # The data is daily. I assume a 24 session.
        v = V/(24*60)
        vm = np.median(v[-40:])
        dp = np.diff(p)
        ss = np.std(dp[-40:])
        return self.slope*(ss*np.abs(trade)/vm)+self.bias
