# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/risk.sig_model.ipynb.

# %% auto 0
__all__ = ['sig_model']

# %% ../../nbs/risk.sig_model.ipynb 4
import pandas as pd
import numpy as np

# %% ../../nbs/risk.sig_model.ipynb 5
class sig_model():
    def __init__(self,data,param):
        self.wsig = param['wvol']
        self.ohlcv = data
    def risk_hat(self):
        
        r = np.diff(np.log(self.ohlcv[:,4]))
        
        # Calculate the mean of the recent returns over the moving average window
        vol = np.std(r[-self.wsig:])
        
        out ={}
        out['vol_hat']  = float(np.round(vol,4))
        return out
