# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/pm.vol_target.ipynb.

# %% auto 0
__all__ = ['vol_target']

# %% ../../nbs/pm.vol_target.ipynb 4
import pandas as pd
import numpy as np

# %% ../../nbs/pm.vol_target.ipynb 5
class vol_target():
    def __init__(self,data,param):
        self.ohlcv = data # this code assumes a very special data array for simplicity
        self.target_vol = param['target_vol']
        self.AUM = param['AUM']
    def allocation(self,expected_return,volatility,price=None):
        if price is None:
            price = self.ohlcv[-1,4] 
        t_scale = round(self.AUM*self.target_vol /price,4)
        n_new = round(t_scale*expected_return/volatility)
        out={}
        out['N'] = n_new
        return out
